// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $notifications from "./routes/notifications.tsx";
import * as $projects_id_ from "./routes/projects/[id].tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $resources from "./routes/resources.tsx";
import * as $resources_index from "./routes/resources/index.tsx";
import * as $resources_inventory from "./routes/resources/inventory.tsx";
import * as $resources_reservations from "./routes/resources/reservations.tsx";
import * as $resources_schedules from "./routes/resources/schedules.tsx";
import * as $users from "./routes/users.tsx";
import * as $Buttons_DeleteButton from "./islands/Buttons/DeleteButton.tsx";
import * as $Buttons_EditItemModal from "./islands/Buttons/EditItemModal.tsx";
import * as $Buttons_NewUserModal from "./islands/Buttons/NewUserModal.tsx";
import * as $Kanban from "./islands/Kanban.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/notifications.tsx": $notifications,
    "./routes/projects/[id].tsx": $projects_id_,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/resources.tsx": $resources,
    "./routes/resources/index.tsx": $resources_index,
    "./routes/resources/inventory.tsx": $resources_inventory,
    "./routes/resources/reservations.tsx": $resources_reservations,
    "./routes/resources/schedules.tsx": $resources_schedules,
    "./routes/users.tsx": $users,
  },
  islands: {
    "./islands/Buttons/DeleteButton.tsx": $Buttons_DeleteButton,
    "./islands/Buttons/EditItemModal.tsx": $Buttons_EditItemModal,
    "./islands/Buttons/NewUserModal.tsx": $Buttons_NewUserModal,
    "./islands/Kanban.tsx": $Kanban,
    "./islands/Sidebar.tsx": $Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
