// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $notifications from "./routes/notifications.tsx";
import * as $projects_id_ from "./routes/projects/[id].tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $resources_index from "./routes/resources/index.tsx";
import * as $resources_inventory from "./routes/resources/inventory.tsx";
import * as $resources_reservations_calendar from "./routes/resources/reservations-calendar.tsx";
import * as $resources_reservations from "./routes/resources/reservations.tsx";
import * as $resources_schedules from "./routes/resources/schedules.tsx";
import * as $tasks_index from "./routes/tasks/index.tsx";
import * as $users from "./routes/users.tsx";
import * as $BoxTree from "./islands/BoxTree.tsx";
import * as $Buttons_CreateNodeModal from "./islands/Buttons/CreateNodeModal.tsx";
import * as $Buttons_DeleteButton from "./islands/Buttons/DeleteButton.tsx";
import * as $Buttons_DeleteNodeModal from "./islands/Buttons/DeleteNodeModal.tsx";
import * as $Buttons_EditItemModal from "./islands/Buttons/EditItemModal.tsx";
import * as $Buttons_EditNodeModal from "./islands/Buttons/EditNodeModal.tsx";
import * as $Buttons_NewGroupButton from "./islands/Buttons/NewGroupButton.tsx";
import * as $Buttons_NewProjectModal from "./islands/Buttons/NewProjectModal.tsx";
import * as $Buttons_NewReservationModal from "./islands/Buttons/NewReservationModal.tsx";
import * as $Buttons_NewScheduleModal from "./islands/Buttons/NewScheduleModal.tsx";
import * as $Buttons_NewTaskModal from "./islands/Buttons/NewTaskModal.tsx";
import * as $Buttons_NewUserModal from "./islands/Buttons/NewUserModal.tsx";
import * as $Buttons_OptionsButton from "./islands/Buttons/OptionsButton.tsx";
import * as $Kanban from "./islands/Kanban.tsx";
import * as $Notifications_NotificationSchedulerIsland from "./islands/Notifications/NotificationSchedulerIsland.tsx";
import * as $Notifications_NotificationToggle from "./islands/Notifications/NotificationToggle.tsx";
import * as $Notifications_NotificationsClient from "./islands/Notifications/NotificationsClient.tsx";
import * as $ProjectsList from "./islands/ProjectsList.tsx";
import * as $ResourceInventory from "./islands/ResourceInventory.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $TasksList from "./islands/TasksList.tsx";
import * as $TuiCalendarIsland from "./islands/TuiCalendarIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/notifications.tsx": $notifications,
    "./routes/projects/[id].tsx": $projects_id_,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/resources/index.tsx": $resources_index,
    "./routes/resources/inventory.tsx": $resources_inventory,
    "./routes/resources/reservations-calendar.tsx":
      $resources_reservations_calendar,
    "./routes/resources/reservations.tsx": $resources_reservations,
    "./routes/resources/schedules.tsx": $resources_schedules,
    "./routes/tasks/index.tsx": $tasks_index,
    "./routes/users.tsx": $users,
  },
  islands: {
    "./islands/BoxTree.tsx": $BoxTree,
    "./islands/Buttons/CreateNodeModal.tsx": $Buttons_CreateNodeModal,
    "./islands/Buttons/DeleteButton.tsx": $Buttons_DeleteButton,
    "./islands/Buttons/DeleteNodeModal.tsx": $Buttons_DeleteNodeModal,
    "./islands/Buttons/EditItemModal.tsx": $Buttons_EditItemModal,
    "./islands/Buttons/EditNodeModal.tsx": $Buttons_EditNodeModal,
    "./islands/Buttons/NewGroupButton.tsx": $Buttons_NewGroupButton,
    "./islands/Buttons/NewProjectModal.tsx": $Buttons_NewProjectModal,
    "./islands/Buttons/NewReservationModal.tsx": $Buttons_NewReservationModal,
    "./islands/Buttons/NewScheduleModal.tsx": $Buttons_NewScheduleModal,
    "./islands/Buttons/NewTaskModal.tsx": $Buttons_NewTaskModal,
    "./islands/Buttons/NewUserModal.tsx": $Buttons_NewUserModal,
    "./islands/Buttons/OptionsButton.tsx": $Buttons_OptionsButton,
    "./islands/Kanban.tsx": $Kanban,
    "./islands/Notifications/NotificationSchedulerIsland.tsx":
      $Notifications_NotificationSchedulerIsland,
    "./islands/Notifications/NotificationToggle.tsx":
      $Notifications_NotificationToggle,
    "./islands/Notifications/NotificationsClient.tsx":
      $Notifications_NotificationsClient,
    "./islands/ProjectsList.tsx": $ProjectsList,
    "./islands/ResourceInventory.tsx": $ResourceInventory,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/TasksList.tsx": $TasksList,
    "./islands/TuiCalendarIsland.tsx": $TuiCalendarIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
