// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $categories from "./routes/categories.tsx";
import * as $expenses from "./routes/expenses.tsx";
import * as $incomes from "./routes/incomes.tsx";
import * as $index from "./routes/index.tsx";
import * as $reports from "./routes/reports.tsx";
import * as $users from "./routes/users.tsx";
import * as $DeleteButton from "./islands/DeleteButton.tsx";
import * as $EditItemModal from "./islands/EditItemModal.tsx";
import * as $NewButton from "./islands/NewButton.tsx";
import * as $NewCategoryModal from "./islands/NewCategoryModal.tsx";
import * as $NewUserModal from "./islands/NewUserModal.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/categories.tsx": $categories,
    "./routes/expenses.tsx": $expenses,
    "./routes/incomes.tsx": $incomes,
    "./routes/index.tsx": $index,
    "./routes/reports.tsx": $reports,
    "./routes/users.tsx": $users,
  },
  islands: {
    "./islands/DeleteButton.tsx": $DeleteButton,
    "./islands/EditItemModal.tsx": $EditItemModal,
    "./islands/NewButton.tsx": $NewButton,
    "./islands/NewCategoryModal.tsx": $NewCategoryModal,
    "./islands/NewUserModal.tsx": $NewUserModal,
    "./islands/Sidebar.tsx": $Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
